language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx
  - jruby-19mode
  - jruby-head
branches:
  only:
    - master
script:
  - bundle exec rspec spec
  - bundle exec rspec integration
after_script:
  - bundle exec coveralls push
